export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAILURE = 'CATEGORY_FAILURE';

export const CATEGORY_ITEM_CREATE = 'CATEGORY_ITEM_CREATE';
export const CATEGORY_LIST_READ = 'CATEGORY_LIST_READ';
export const CATEGORY_ITEM_UPDATE = 'CATEGORY_ITEM_UPDATE';
export const CATEGORY_ITEM_DELETE = 'CATEGORY_ITEM_DELETE';
export const CATEGORY_ITEM_TEMP_CREATE = 'CATEGORY_ITEM_TEMP_CREATE';
export const CATEGORY_ITEM_TEMP_DELETE = 'CATEGORY_ITEM_TEMP_DELETE';
